DROP TABLE IF EXISTS study_languages;
CREATE TABLE study_languages (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
study_language VARCHAR(225) NOT NULL,
study_hour VARCHAR(225) NOT NULL
);



DROP TABLE IF EXISTS study_contents;
CREATE TABLE study_contents (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
study_content VARCHAR(225) NOT NULL,
study_hour VARCHAR(225) NOT NULL
);
